-- DROP TABLE IF EXISTS 'users';
DROP TABLE IF EXISTS 'surveys';
DROP TABLE IF EXISTS 'survey_responses';

-- create TABLE users (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   name TEXT UNIQUE NOT NULL
-- );

CREATE TABLE surveys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  available_places INTEGER NOT NULL DEFAULT 30,
  survey_responses_count INTEGER NOT NULL DEFAULT 0,
  user INTEGER NOT NULL
);

CREATE TABLE survey_responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey INTEGER NOT NULL,
  user INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT unique_user_in_survey UNIQUE (survey, user)
);
